routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Jobs\sndmailjob;
use Carbon\Carbon;
use App\User;


Route::get('/', function () {
    return view('welcome');
});

    Route::resource('home','UserController');
    Route::resource('post','PostController');
    Route::get('login','UserController@login')->name('login');
    Route::post('login','UserController@login')->name('login');
    Route::get('/logout','UserController@logout')->name('logout');
    Route::get('comment/{id}','PostController@comment')->name('comment');
    Route::get('countrywpost/{id}','PostController@countrywpost')->name('countrywpost');
    Route::get('onlyimage/','PostController@onlyimage')->name('onlyimage');
    Route::get('onlyvideo/','PostController@onlyvideo')->name('onlyvideo');
    Route::get('like/{id}','PostController@like')->name('like');
    Route::get('unlike/{id}','PostController@unlike')->name('unlike');

resources/views/addpost.blade.php
@extends('layouts.master')
@section('content')
    <form action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="">Add Phosts</label>
            <input type="file" class="form-control @error('post_url') is-invalid @enderror" id="post_url"
                   name="post_url">
            @error('post_url')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
        <div class="form-group">
            <label for="">Title</label>
            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title">
            @error('title')
            <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/countrywpost.blade.php
@extends('layouts.master')
@section('content')
    <a type="submit" href="{{route('post.index')}}" class="btn btn-primary mb-5">Back</a>

    <div class="card-columns">
        @foreach($posts as $post)
            <div class="card " style="width: 300px">
                {{--                    @foreach($users as $userss)--}}
                {{--                        @if($userss->id==$post->user_id)--}}
                <img src="{{url('/storage/'.$post->user->profile_image)}}" style="width: 60px;"
                     class="rounded-circle img-thumbnail">
                <a class="card-text">Posted By : {{$post->user->name}}</a>
                {{--                        @endif--}}
                {{--                    @endforeach--}}
                <hr>
                <img class="card-img-top" src="{{url('/storage/'.$post->post_url)}}">
                <div class="card-body">
                    <div class="interaction">
                        @if(sizeof($post->users)  == null)
                            <a href="{{url("/like/{$post->id}")}}" class="btn btn-sm btn-success mb-2">like</a>
                        @else
                            <a href="{{url("/like/{$post->id}")}}" class="btn btn-sm btn-danger mb-2">Unlike</a>
                        @endif
                        <form method="post" action="{{url("/comment/{$post->id}")}}" class="form-group">
                            @csrf
                            @method('get')
                            <input type="text" class="form-control" name="comment" id="comment"
                                   placeholder="Comment...">
                            <input type="submit" class="form-control" name="submit" value="submit">
                        </form>
                        @foreach($post->comments as $comment)
                            {{--                                @if($post->id==$comment->post_id)--}}
                            {{--                                        @foreach($users as $userss)--}}
                            {{--                                            @if($userss->id==$comment->user_id)--}}
                            <img src="{{url('/storage/'.$comment->user->profile_image)}}" style="width: 45px;"
                                 class="rounded-circle img-thumbnail">
                            <small><a class="card-text">{{$comment->user->name}}<br></a></small>
                            {{--                                            @endif--}}
                            {{--                                        @endforeach--}}
                            <small>{{$comment->comment}}<br></small>
                            <hr>
                            {{--                                @endif--}}
                        @endforeach
                        @if(Auth::user()==$post->user)
                            <form action="/post/{{$post->id}}" method="post">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger form-control">Delete</button>
                            </form>
                        @endif
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="offset-lg-4 col-lg-4 col-sm-6 col-12 main-section text-center">
                <div class="row">
                    <div class="col-lg-12 col-sm-12 col-12 profile-header"></div>
                </div>
                <div class="row user-detail">
                    <div class="col-lg-12 col-sm-12 col-12">
                        <img src="{{url('/storage/'.$user->profile_image)}}" class="rounded-circle img-thumbnail">
                        <h5>{{$user->name}}</h5>
                        <h5>{{$user->username}}</h5>
                        <p>{{$user->dob}}</p>
{{--                        <p>{{dd(Url::current())}}</p>--}}
                        <hr>
                        <a class="btn btn-outline-success form-control" href="{{ route('post.create') }}">Add post</a>
                        <hr>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle form-control" type="button"
                                    id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                Country
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                @foreach($country as $country)
                                    <form method="post" class="form" action="{{url("/countrywpost/{$country->id}")}}">
                                        @csrf
                                        @method('get')
                                        <button class="btn btn-outline-primary form-control" type="submit"
                                                value="{{ $country->id }}">{{ $country->name }}</button>
                                    </form>
                                @endforeach
                            </div>
                        </div>
                        <hr>
                        <form method="post" class="form" action="{{route('onlyimage')}}">
                            @csrf
                            @method('get')
                            <button class="btn btn-outline-dark form-control" type="submit" value="">Image</button>
                        </form>
                        <hr>
                        <form method="post" class="form" action="{{route('onlyvideo')}}">
                            @csrf
                            @method('get')
                            <button class="btn btn-outline-warning form-control" type="submit" value="">Videos</button>
                        </form>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-columns py-3">
        @foreach($posts as $post)
            <div class="card mx-2 " style="width: 350px">
                {{--                @foreach($users as $userss)--}}
                {{--                    @if($userss->id==$post->user_id)--}}
                <img src="{{url('/storage/'.$post->user->profile_image)}}" style="width: 60px;"
                     class="rounded-circle img-thumbnail">
                <a class="card-text">Posted By : {{$post->user->name}}</a>
                {{--                    @endif--}}
                {{--                @endforeach--}}
                <hr>
                <img class="card-img-top" src="{{url('/storage/'.$post->post_url)}}">
                {{--                <a class="card-text">{{$posts->user->user_id}}</a>--}}
                <div class="card-body">
                    <div class="interaction">
                        @if(sizeof($post->users)  == null)
                            {{--                            {{dd('unlike',$post->like)}}--}}
                            <a href="{{url("/like/{$post->id}")}}" class="btn btn-sm btn-success mb-2">like</a>
                        @else
                            <a href="{{url("/like/{$post->id}")}}" class="btn btn-sm btn-danger mb-2">Unlike</a>
                            {{--                            {{dd('like',$post->like)}}--}}
                        @endif
                        <form method="post" action="{{url("/comment/{$post->id}")}}" class="form-group">
                            @csrf
                            @method('get')
                            <input type="text" class="form-control" name="comment" id="comment"
                                   placeholder="Comment...">
                            <input type="submit" class="form-control" name="submit" value="submit">
                        </form>
                        @foreach($post->comments as $comment)
                            {{--                            {{dd($post->user->profile_image)}}--}}
                            {{--                            @if($post->id==$comment->post_id)--}}
                            {{--                                    @foreach($users as $userss)--}}
                            {{--                                        @if($userss->id==$comment->user_id)--}}
                            <img src="{{url('/storage/'.$comment->user->profile_image)}}" style="width: 45px;"
                                 class="rounded-circle img-thumbnail">
                            <small><a class="card-text">{{$comment->user->name}}<br></a></small>
                            {{--                                        @endif--}}
                            {{--                                    @endforeach--}}
                            <small>{{$comment->comment}}<br></small>
                            <hr>
                            {{--                            @endif--}}
                        @endforeach
                        @if(Auth::id()==$post->user_id)
                            <form action="/post/{{$post->id}}" method="post">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger form-control">Delete</button>
                            </form>
                        @endif
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/editprofile.blade.php
@extends('layouts.master')
@section('content')
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <form class="form" action="{{ route('home.update',[$user->id]) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PUT')
    <div class="container">
        <div class="row flex-lg-nowrap">
            <div class="col">
                <div class="row">
                    <div class="col mb-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="e-profile">
                                    <div class="row">
                                        <div class="col-12 col-sm-auto mb-3">
                                            <div class="mx-auto" style="width: 140px;">
                                                <div class="d-flex justify-content-center align-items-center rounded" style="height: 140px; background-color: rgb(233, 236, 239);">
                                                   <img src="{{url('/storage/'.$user->profile_image)}}" style="height: 140px;width: 140px;">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col d-flex flex-column flex-sm-row justify-content-between mb-3">
                                            <div class="text-center text-sm-left mb-2 mb-sm-0">
                                                <h4 class="pt-sm-2 pb-1 mb-0 text-nowrap">{{$user->name}}</h4>
                                                <p class="mb-0">{{$user->username}}</p>
                                                <div class="text-muted"><small>{{$user->dob}}</small></div>
                                                <div class="mt-2">
                                                    <button class="btn btn-primary" type="button">
                                                        <i class="fa fa-fw fa-camera"></i>
                                                        <input type="file" name="profile_image" id="profile_image" value="">
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <ul class="nav nav-tabs">
                                        <li class="nav-item"><a href="" class="active nav-link">Settings</a></li>
                                    </ul>
                                    <div class="tab-content pt-3">
                                        <div class="tab-pane active">
                                                <div class="row">
                                                    <div class="col">
                                                        <div class="row">
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <label>Full Name</label>
                                                                    <input class="form-control @error('name') is-invalid @enderror" type="text" name="name" placeholder="John Smith" value="{{$user->name}}">
                                                                    @error('name')
                                                                    <span class="invalid-feedback" role="alert">
                                                                        <strong>{{ $message }}</strong>
                                                                    </span>
                                                                    @enderror
                                                                </div>
                                                            </div>
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <label>Username</label>
                                                                    <input class="form-control @error('username') is-invalid @enderror" type="text" name="username" placeholder="johnny.s" value="{{$user->username}}">
                                                                    @error('username')
                                                                    <span class="invalid-feedback" role="alert">
                                                                        <strong>{{ $message }}</strong>
                                                                    </span>
                                                                    @enderror
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <label>Email</label>
                                                                    <input class="form-control @error('email') is-invalid @enderror" type="email" name="email" id="email" value="{{$user->email}}">
                                                                    @error('email')
                                                                    <span class="invalid-feedback" role="alert">
                                                                        <strong>{{ $message }}</strong>
                                                                    </span>
                                                                    @enderror
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <label>Date of Birth</label>
                                                                    <input class="form-control @error('date') is-invalid @enderror" type="date" name="date" id="date" value="{{$user->dob}}">
                                                                    @error('date')
                                                                    <span class="invalid-feedback" role="alert">
                                                                        <strong>{{ $message }}</strong>
                                                                    </span>
                                                                    @enderror
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col d-flex justify-content-end">
                                                        <a href="{{route('post.index')}}" class="btn btn-primary mr-3">Cancle</a>
                                                        <button class="btn btn-primary" type="submit">Save Changes</button>
                                                    </div>
                                                </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-3 mb-3">
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="px-xl-3">
                                    <button class="btn btn-block btn-secondary">
                                        <i class="fa fa-sign-out"></i>
                                        <a href="{{route('logout')}}" class="text-white">Logout</a>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    </form>
@endsection

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
        <title>@yield('title')</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
    <body>
    <div class="container">
        <div class="row my-5">
            <div class="col-sm-6">
                <h2>Sign Up</h2>
                <form action="{{ route('home.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name : </label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="username">User Name : </label>
                        <input type="text" class="form-control @error('username') is-invalid @enderror" name="username" id="username">
                        @error('username')
                        <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email : </label>
                        <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" id="email">
                        @error('email')
                        <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="password">Password : </label>
                        <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" id="password">
                        @error('password')
                        <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="date">Date of Birth : </label>
                        <input type="date" class="form-control @error('date') is-invalid @enderror" name="date" id="date">
                        @error('date')
                        <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Country : </label>
                        <select class="custom-select @error('country') is-invalid @enderror" name="country" id="country">
                            <option hidden value="">Select Country</option>
                            @foreach($country as $country)
                                <option value="{{ $country->id }}">{{ $country->name }}</option>
                            @endforeach
                        </select>
                        @error('country')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Profile image : </label>
                        <input type="file" name="profile_image" id="profile" class="form-control @error('profile_image') is-invalid @enderror" placeholder="Enter image" aria-describedby="helpId">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-sm-6">
                <h2>Sign In</h2>
                <form action="{{route('login')}}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="email">Email : </label>
                        <input type="email" class="form-control @error('email1') is-invalid @enderror" name="email1" id="email">
                        @error('email1')
                        <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="password">Password : </label>
                        <input type="password" class="form-control @error('password1') is-invalid @enderror" name="password1" id="password">
                        @error('password1')
                        <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    </body>
    </html>